### ISSUE TITLE
Install sql failure

### ISSUE THREAD

**Issue by onyxnz** [krazzer/kikcms#21]
When trying to install the SQL file to a new database:
INSERT INTO `cms_page_language` VALUES ('3', '3', 'en', '1', 'Home', 'home', null, null, null),
                                       ('4', '4', 'en', '1', 'Pagina 2', 'pagina-2', null, null, null),
                                       ('5', '5', 'en', '1', 'Hoofdmenu', null, null, null, null),
                                       ('7', '4', 'nl', '1', 'Pagina 2 NL', 'pagina-2-nl', null, null, null),
                                       ('8', '5', 'nl', '1', 'Hoofdmenu', null, null, null, null);
MySQL said: Documentation

#1452 - Cannot add or update a child row: a foreign key constraint fails (`newdb`.`cms_page_language`, CONSTRAINT `cms_page_language_ibfk_2` FOREIGN KEY (`page_id`) REFERENCES `cms_page` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

**Comment by krazzer** [comment]
It looks like the cms_page entries are missing. Did you run the complete sql file as a whole?

**Comment by onyxnz** [comment]
Yes, just using PHPMyAdmin to do a direct Import of the SQL file.

**Comment by krazzer** [comment]
I get the exact same error if I remove the disabling of the FK checks `SET FOREIGN_KEY_CHECKS = 0;`

PHPMyAdmin probably doesn't allow that in a query.

I will check if I can change the query so it doesn't need to disable the FK checks, which I find to be neater anyway.

**Comment by krazzer** [comment]
Fixed it. I updated the boilerplate repo. Thanks for reporting!
