### ISSUE TITLE
Github clone failure

### ISSUE THREAD

**Issue by onyxnz** [krazzer/kikcms#22]
git clone git@github.com:krazzer/kikcms-boilerplate.git . && rm -rf ./.git && sh createdirs.sh~
Cloning into '.'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by krazzer** [comment]
I changed the readme to use https instead of ssh, that should work
