### ISSUE TITLE
cant install from boilerplate and composer

### ISSUE THREAD

**Issue by aldonesia** [krazzer/kikcms#4]
1. Let's get some boilerplate code, run this in the directory you want your project to be: git archive --format=tar --remote=git@github.com:krazzer/boilerplate.git HEAD | tar xf - && sh createdirs.sh

at this point I got permission dennied, and also im clone kikcms project from https://github.com/krazzer/kikcms-boilerplate

3. Run composer install

at this point i got error, permission denied from bitbucket kiksaus kikcms

**Comment by krazzer** [comment]
Hey @aldonesia, thanks for submitting the very first issue 😄

I'll check it out, there's probably something still pointing to the old bitbucket location

**Comment by aldonesia** [comment]
Has it been fixed?

**Comment by krazzer** [comment]
Fixed it
