### ISSUE TITLE
Phalcon v4 compatibility

### ISSUE THREAD

**Issue by orbex** [krazzer/kikcms#8]
Hi,
any plans to refactor this to comply with Phalcon v4?
Am willing to contribute/collaborate.

**Comment by krazzer** [comment]
@orbex Absolutely, as soon as my hosting company starts supporting it, I will update to Phalcon 4.

**Comment by orbex** [comment]
Have a server up and running with Phalcon v4 @ vps.clsystems.nl
Could setup some test-domain to work with.

**Comment by krazzer** [comment]
Setting up a test env is not the problem, it's more time thing. Currently I have a lot of websites running on the CMS on a server stuck on Phalcon v3. If I would support v4, I would have to maintain two separate versions.

When the server supports v4, I would just update to v4 and let that be the default version.

On the other hand, if you are willing to maintain the v4 version, then let's do it.
