### ISSUE TITLE
using php-fpm / apcu_fetch error

### ISSUE THREAD

**Issue by rnvijay** [krazzer/kikcms#9]
Just trying first time, i am using php-fpm, (Cent OS) .. on initial install, i get following issue - any ideas? thanks

PHP Fatal error:  Uncaught RuntimeException: Call to undefined function apcu_fetch() in ../kikcms/vendor/kiksaus/kikcms/src/Services/NamespaceService.php:31

**Comment by krazzer** [comment]
@rnvijay yeah the apcu module is missing
